# Generated by Django 4.2 on 2023-04-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userdata_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
