# Generated by Django 4.2 on 2023-04-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userdata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_pic'),
        ),
    ]
