# Generated by Django 4.2 on 2023-04-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userdata_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
