# Generated by Django 4.2 on 2023-04-11 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userdata_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
