# Generated by Django 4.2 on 2023-04-17 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=20)),
                ('flag', models.BooleanField(default=False)),
                ('coin_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_receiver', to=settings.AUTH_USER_MODEL)),
                ('coin_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
