# Generated by Django 4.2 on 2023-04-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_giftsent_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftsent',
            name='coin',
            field=models.IntegerField(),
        ),
    ]
