# Generated by Django 4.2 on 2023-04-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='total_match',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='total_win_match',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
