# Generated by Django 4.2 on 2023-04-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userdata_total_match_userdata_total_win_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='total_match',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='total_win_match',
        ),
    ]
